### POST request to example server
POST http://lb-bc5ea2c3.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pablo Batalla with Kafka Test",
  "email": "kafka_test@gmail.com",
  "address": "Argentina",
  "dateOfBirth": "1985-09-09",
  "registeredDate": "2025-03-13"
}

###